import JSZip from 'jszip';
import { mapWithConcurrency } from '../utils/concurrency';
import type { CollectedImage, DownloadedImageMetadata, MetadataFile } from '../types';

export interface ZipResult {
  blob: Blob;
  metadata: DownloadedImageMetadata[];
  summary: MetadataFile['summary'];
}

function sanitizeTitle(text: string): string {
  return text
    .replace(/[^a-zA-Z0-9\p{L}]+/gu, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/[\\/:*?"<>|]/g, '')
    .toLowerCase()
    .slice(0, 40) || 'untitled';
}

function categorize(image: CollectedImage): string {
  const ext = image.extension;
  const size = Math.max(
    image.width || image.displayedWidth || 0,
    image.height || image.displayedHeight || 0,
  );

  if (ext === 'svg') return 'vectors';
  if (size < 150) return 'thumbnails_and_icons';
  if (size >= 500 && ['jpg', 'jpeg', 'webp', 'avif', 'bmp'].includes(ext)) return 'photos';
  return 'other';
}

function smartName(
  domain: string,
  pageTitle: string,
  index: number,
  ext: string,
): string {
  const prefix = domain.replace(/[^a-zA-Z0-9-]/g, '') || 'page';
  const title = sanitizeTitle(pageTitle);
  const num = String(index + 1).padStart(3, '0');
  return `${prefix}_${title}_${num}.${ext}`;
}

export async function createZip(
  images: CollectedImage[],
  fetchBlob: (image: CollectedImage) => Promise<Blob>,
  page: { url: string; title: string; domain: string },
  onProgress?: (completed: number, total: number) => void,
): Promise<ZipResult> {
  const zip = new JSZip();
  const folderCounts: Record<string, number> = {};
  let completed = 0;

  const metadata = await mapWithConcurrency(images, 6, async (image) => {
    const category = categorize(image);
    folderCounts[category] = (folderCounts[category] ?? 0) + 1;
    const count = folderCounts[category];
    const filename = smartName(page.domain, page.title, count, image.extension);
    const archiveFilename = `${category}/${filename}`;
    try {
      const blob = await fetchBlob(image);
      zip.file(archiveFilename, blob, { binary: true, compression: 'STORE' });
      onProgress?.(++completed, images.length);
      return {
        ...image,
        archiveFilename,
        byteSize: blob.size,
        downloadedMimeType: blob.type || image.mimeType,
        status: 'downloaded' as const,
      };
    } catch (error) {
      onProgress?.(++completed, images.length);
      const message = error instanceof Error ? error.message : 'Unknown error';
      console.error(`[ZIP] Failed to fetch ${image.url}: ${message}`);
      return {
        ...image,
        archiveFilename,
        byteSize: null,
        downloadedMimeType: '',
        status: 'failed' as const,
        error: message,
      };
    }
  });

  const downloaded = metadata.filter((item) => item.status === 'downloaded');
  const failed = metadata.filter((item) => item.status === 'failed');

  const totalBytes = downloaded.reduce((total, item) => total + (item.byteSize ?? 0), 0);

  const summary = {
    selected: images.length,
    downloaded: downloaded.length,
    failed: failed.length,
    totalBytes,
  };

  const metadataFile: MetadataFile = {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    page,
    summary,
    images: metadata,
  };

  zip.file('metadata.json', JSON.stringify(metadataFile, null, 2), {
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  const infoLines = [
    `Source: ${page.title}`,
    `URL: ${page.url}`,
    `Domain: ${page.domain}`,
    `Exported: ${new Date().toISOString()}`,
    '',
    `Summary:`,
    `  Selected: ${images.length}`,
    `  Downloaded: ${downloaded.length}`,
    `  Failed: ${failed.length}`,
    `  Total size: ${(totalBytes / 1024).toFixed(1)} KB`,
    '',
    `Folders:`,
    `  vectors/ — SVG assets (${folderCounts.vectors ?? 0})`,
    `  photos/ — large photos >500px (${folderCounts.photos ?? 0})`,
    `  thumbnails_and_icons/ — small assets <150px (${folderCounts.thumbnails_and_icons ?? 0})`,
    `  other/ — remaining assets (${folderCounts.other ?? 0})`,
    '',
    `Generated by Grab — Image Collector`,
  ].join('\n');

  zip.file('info.txt', infoLines, { compression: 'DEFLATE', compressionOptions: { level: 6 } });

  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'STORE',
  });

  return { blob, metadata, summary };
}
